//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Computer_Era_X.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Computer_Era_X.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About the author.
        /// </summary>
        public static string _ {
            get {
                return ResourceManager.GetString("+", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Author.
        /// </summary>
        public static string AboutTheAuthor {
            get {
                return ResourceManager.GetString("AboutTheAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add assembly.
        /// </summary>
        public static string AddAssembly {
            get {
                return ResourceManager.GetString("AddAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Air flow.
        /// </summary>
        public static string AirFlow {
            get {
                return ResourceManager.GetString("AirFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Assembling added.
        /// </summary>
        public static string AssemblingAdded {
            get {
                return ResourceManager.GetString("AssemblingAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Assembling changed.
        /// </summary>
        public static string AssemblingChanged {
            get {
                return ResourceManager.GetString("AssemblingChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The specified name is already in the list of assemblies..
        /// </summary>
        public static string AssemblyMessage1 {
            get {
                return ResourceManager.GetString("AssemblyMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Assembly name.
        /// </summary>
        public static string AssemblyName {
            get {
                return ResourceManager.GetString("AssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type.
        /// </summary>
        public static string AssemblyType {
            get {
                return ResourceManager.GetString("AssemblyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bank &quot;Retribution&quot;.
        /// </summary>
        public static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Before.
        /// </summary>
        public static string Before {
            get {
                return ResourceManager.GetString("Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BIOS.
        /// </summary>
        public static string BIOS {
            get {
                return ResourceManager.GetString("BIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Welcome to the Riveting Yourself computer parts store! Would you like to buy something?.
        /// </summary>
        public static string BuildingsMessage1 {
            get {
                return ResourceManager.GetString("BuildingsMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Built-in fans.
        /// </summary>
        public static string BuiltInFans {
            get {
                return ResourceManager.GetString("BuiltInFans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bus park №1.
        /// </summary>
        public static string BusParkNumberOne {
            get {
                return ResourceManager.GetString("BusParkNumberOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Buy.
        /// </summary>
        public static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Buying a {0}.
        /// </summary>
        public static string BuyingAX {
            get {
                return ResourceManager.GetString("BuyingAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By bike.
        /// </summary>
        public static string ByBike {
            get {
                return ResourceManager.GetString("ByBike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By car.
        /// </summary>
        public static string ByCar {
            get {
                return ResourceManager.GetString("ByCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By public transport.
        /// </summary>
        public static string ByPublicTransport {
            get {
                return ResourceManager.GetString("ByPublicTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Case.
        /// </summary>
        public static string Case {
            get {
                return ResourceManager.GetString("Case", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cells.
        /// </summary>
        public static string Cells {
            get {
                return ResourceManager.GetString("Cells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chipset.
        /// </summary>
        public static string Chipset {
            get {
                return ResourceManager.GetString("Chipset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shop &quot;Spike yourself&quot;.
        /// </summary>
        public static string ComponentStoreFullName {
            get {
                return ResourceManager.GetString("ComponentStoreFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Spike yourself.
        /// </summary>
        public static string ComponentStoreName {
            get {
                return ResourceManager.GetString("ComponentStoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Computer.
        /// </summary>
        public static string Computer {
            get {
                return ResourceManager.GetString("Computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection interface.
        /// </summary>
        public static string ConnectionInterface {
            get {
                return ResourceManager.GetString("ConnectionInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Continue.
        /// </summary>
        public static string ContinueGame {
            get {
                return ResourceManager.GetString("ContinueGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cost.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Central processing unit.
        /// </summary>
        public static string CPU {
            get {
                return ResourceManager.GetString("CPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CPU cooler.
        /// </summary>
        public static string CPUCooler {
            get {
                return ResourceManager.GetString("CPUCooler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CPU frequency.
        /// </summary>
        public static string CPUFrequency {
            get {
                return ResourceManager.GetString("CPUFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Creative.
        /// </summary>
        public static string CreativeScenario {
            get {
                return ResourceManager.GetString("CreativeScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Creator&apos;s Hand.
        /// </summary>
        public static string CreativeScenarioPaymentInitiator {
            get {
                return ResourceManager.GetString("CreativeScenarioPaymentInitiator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gift.
        /// </summary>
        public static string CreativeScenarioPaymentName {
            get {
                return ResourceManager.GetString("CreativeScenarioPaymentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date of service contract.
        /// </summary>
        public static string DateOfServiceContract {
            get {
                return ResourceManager.GetString("DateOfServiceContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete all notifications.
        /// </summary>
        public static string DeleteAllNotifications {
            get {
                return ResourceManager.GetString("DeleteAllNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Distance to city center.
        /// </summary>
        public static string DistanceToCityCenter {
            get {
                return ResourceManager.GetString("DistanceToCityCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на EFI support.
        /// </summary>
        public static string EFISupport {
            get {
                return ResourceManager.GetString("EFISupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No central processing unit.
        /// </summary>
        public static string ErrorСodeNoCPU {
            get {
                return ResourceManager.GetString("ErrorСodeNoCPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No CPU cooler.
        /// </summary>
        public static string ErrorСodeNoCPUCooler {
            get {
                return ResourceManager.GetString("ErrorСodeNoCPUCooler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No hard disk drive.
        /// </summary>
        public static string ErrorСodeNoHDD {
            get {
                return ResourceManager.GetString("ErrorСodeNoHDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No motherboard.
        /// </summary>
        public static string ErrorСodeNoMotherboard {
            get {
                return ResourceManager.GetString("ErrorСodeNoMotherboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No power supply unit.
        /// </summary>
        public static string ErrorСodeNoPowerSupply {
            get {
                return ResourceManager.GetString("ErrorСodeNoPowerSupply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No random access memory.
        /// </summary>
        public static string ErrorСodeNoRAM {
            get {
                return ResourceManager.GetString("ErrorСodeNoRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No video card.
        /// </summary>
        public static string ErrorСodeNoVideoСard {
            get {
                return ResourceManager.GetString("ErrorСodeNoVideoСard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ok.
        /// </summary>
        public static string ErrorСodeOk {
            get {
                return ResourceManager.GetString("ErrorСodeOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fare payment.
        /// </summary>
        public static string FarePayment {
            get {
                return ResourceManager.GetString("FarePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Form factor.
        /// </summary>
        public static string FormFactor {
            get {
                return ResourceManager.GetString("FormFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Found on the road.
        /// </summary>
        public static string FoundOnTheRoad {
            get {
                return ResourceManager.GetString("FoundOnTheRoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Free.
        /// </summary>
        public static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Frequency.
        /// </summary>
        public static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на It turns out walking in the air is useful not only for health but also for pocket. You found {0} {1} on the road.
        /// </summary>
        public static string GameMessage1 {
            get {
                return ResourceManager.GetString("GameMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sorry buddy, no money, no goods..
        /// </summary>
        public static string GameMessage2 {
            get {
                return ResourceManager.GetString("GameMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Thank you for buying {0}, a good choice!.
        /// </summary>
        public static string GameMessage3 {
            get {
                return ResourceManager.GetString("GameMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hard disk drive.
        /// </summary>
        public static string HDD {
            get {
                return ResourceManager.GetString("HDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Headphone jack.
        /// </summary>
        public static string HeadphoneJack {
            get {
                return ResourceManager.GetString("HeadphoneJack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Heat dissipation.
        /// </summary>
        public static string HeatDissipation {
            get {
                return ResourceManager.GetString("HeatDissipation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hour.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hz.
        /// </summary>
        public static string Hz {
            get {
                return ResourceManager.GetString("Hz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Install.
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Installation.
        /// </summary>
        public static string Installation {
            get {
                return ResourceManager.GetString("Installation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Installation of components.
        /// </summary>
        public static string InstallationOfComponents {
            get {
                return ResourceManager.GetString("InstallationOfComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Installed.
        /// </summary>
        public static string Installed {
            get {
                return ResourceManager.GetString("Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Interface.
        /// </summary>
        public static string Interface {
            get {
                return ResourceManager.GetString("Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid scenario configuration value.
        /// </summary>
        public static string InvalidScenarioConfigurationValue {
            get {
                return ResourceManager.GetString("InvalidScenarioConfigurationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invested.
        /// </summary>
        public static string Invested {
            get {
                return ResourceManager.GetString("Invested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на In your pocket.
        /// </summary>
        public static string InYourPocket {
            get {
                return ResourceManager.GetString("InYourPocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на KB/s.
        /// </summary>
        public static string KBs {
            get {
                return ResourceManager.GetString("KBs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kbyte.
        /// </summary>
        public static string Kbyte {
            get {
                return ResourceManager.GetString("Kbyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Keyboard.
        /// </summary>
        public static string Keyboard {
            get {
                return ResourceManager.GetString("Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Launch.
        /// </summary>
        public static string Launch {
            get {
                return ResourceManager.GetString("Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Liquid cooling support.
        /// </summary>
        public static string LiquidCoolingSupport {
            get {
                return ResourceManager.GetString("LiquidCoolingSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Local disk.
        /// </summary>
        public static string LocalDisk {
            get {
                return ResourceManager.GetString("LocalDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Main.
        /// </summary>
        public static string MainScenario {
            get {
                return ResourceManager.GetString("MainScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parents.
        /// </summary>
        public static string MainScenarioPaymentInitiator {
            get {
                return ResourceManager.GetString("MainScenarioPaymentInitiator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Starting capital.
        /// </summary>
        public static string MainScenarioPaymentName {
            get {
                return ResourceManager.GetString("MainScenarioPaymentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum frame refresh rate.
        /// </summary>
        public static string MaximumFrameRefreshRate {
            get {
                return ResourceManager.GetString("MaximumFrameRefreshRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum rotation speed.
        /// </summary>
        public static string MaximumRotationSpeed {
            get {
                return ResourceManager.GetString("MaximumRotationSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum volume.
        /// </summary>
        public static string MaximumVolume {
            get {
                return ResourceManager.GetString("MaximumVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum working temperature.
        /// </summary>
        public static string MaximumWorkingTemperature {
            get {
                return ResourceManager.GetString("MaximumWorkingTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Memory.
        /// </summary>
        public static string Memory {
            get {
                return ResourceManager.GetString("Memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Memory type.
        /// </summary>
        public static string MemoryType {
            get {
                return ResourceManager.GetString("MemoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Microphone jack.
        /// </summary>
        public static string MicrophoneJack {
            get {
                return ResourceManager.GetString("MicrophoneJack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minimum rotation speed.
        /// </summary>
        public static string MinimumRotationSpeed {
            get {
                return ResourceManager.GetString("MinimumRotationSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minute.
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Modified assembly.
        /// </summary>
        public static string ModifiedAssembly {
            get {
                return ResourceManager.GetString("ModifiedAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Money.
        /// </summary>
        public static string Money {
            get {
                return ResourceManager.GetString("Money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Monitor.
        /// </summary>
        public static string Monitor {
            get {
                return ResourceManager.GetString("Monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Motherboard.
        /// </summary>
        public static string Motherboard {
            get {
                return ResourceManager.GetString("Motherboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Motherboard type.
        /// </summary>
        public static string MotherboardType {
            get {
                return ResourceManager.GetString("MotherboardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mouse.
        /// </summary>
        public static string Mouse {
            get {
                return ResourceManager.GetString("Mouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Moving in space and time.
        /// </summary>
        public static string MovingInSpaceAndTime {
            get {
                return ResourceManager.GetString("MovingInSpaceAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Multi-core processor support.
        /// </summary>
        public static string MultiCoreProcessorSupport {
            get {
                return ResourceManager.GetString("MultiCoreProcessorSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Nests.
        /// </summary>
        public static string Nests {
            get {
                return ResourceManager.GetString("Nests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Network card speed.
        /// </summary>
        public static string NetworkCardSpeed {
            get {
                return ResourceManager.GetString("NetworkCardSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Game.
        /// </summary>
        public static string NewGame {
            get {
                return ResourceManager.GetString("NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Noise level.
        /// </summary>
        public static string NoiseLevel {
            get {
                return ResourceManager.GetString("NoiseLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No player name entered.
        /// </summary>
        public static string NoPlayerNameEntered {
            get {
                return ResourceManager.GetString("NoPlayerNameEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Normal speed.
        /// </summary>
        public static string NormalSpeed {
            get {
                return ResourceManager.GetString("NormalSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No scenario selected.
        /// </summary>
        public static string NoScenarioSelected {
            get {
                return ResourceManager.GetString("NoScenarioSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not limited.
        /// </summary>
        public static string NotLimited {
            get {
                return ResourceManager.GetString("NotLimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No value selected in scenario settings.
        /// </summary>
        public static string NoValueSelectedInScenarioSettings {
            get {
                return ResourceManager.GetString("NoValueSelectedInScenarioSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of cores.
        /// </summary>
        public static string NumberOfCores {
            get {
                return ResourceManager.GetString("NumberOfCores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of IDE 4 pins.
        /// </summary>
        public static string NumberOfIDE4Pins {
            get {
                return ResourceManager.GetString("NumberOfIDE4Pins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of IDE sockets.
        /// </summary>
        public static string NumberOfIDESockets {
            get {
                return ResourceManager.GetString("NumberOfIDESockets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of PCI-E 6 + 2 pins.
        /// </summary>
        public static string NumberOfPCIE6plus2Pins {
            get {
                return ResourceManager.GetString("NumberOfPCIE6plus2Pins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of PCI-Express x16 buses.
        /// </summary>
        public static string NumberOfPCIExpressX16Buses {
            get {
                return ResourceManager.GetString("NumberOfPCIExpressX16Buses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of PCI-Express x1 buses.
        /// </summary>
        public static string NumberOfPCIExpressX1Buses {
            get {
                return ResourceManager.GetString("NumberOfPCIExpressX1Buses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of PCI-Express x4 buses.
        /// </summary>
        public static string NumberOfPCIExpressX4Buses {
            get {
                return ResourceManager.GetString("NumberOfPCIExpressX4Buses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of PCI-Express x8 buses.
        /// </summary>
        public static string NumberOfPCIExpressX8Buses {
            get {
                return ResourceManager.GetString("NumberOfPCIExpressX8Buses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of pins CPU 4 + 4.
        /// </summary>
        public static string NumberOfPinsCPU4plus4 {
            get {
                return ResourceManager.GetString("NumberOfPinsCPU4plus4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of pins IDE 4 Floppy.
        /// </summary>
        public static string NumberOfPinsIDE4Floppy {
            get {
                return ResourceManager.GetString("NumberOfPinsIDE4Floppy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of SATA 15 pins.
        /// </summary>
        public static string NumberOfSATA15Pins {
            get {
                return ResourceManager.GetString("NumberOfSATA15Pins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of SATA 2.0 sockets.
        /// </summary>
        public static string NumberOfSATA20Sockets {
            get {
                return ResourceManager.GetString("NumberOfSATA20Sockets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of SATA 3.0 sockets.
        /// </summary>
        public static string NumberOfSATA30Sockets {
            get {
                return ResourceManager.GetString("NumberOfSATA30Sockets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of slots.
        /// </summary>
        public static string NumberOfSlots {
            get {
                return ResourceManager.GetString("NumberOfSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of sockets.
        /// </summary>
        public static string NumberOfSockets {
            get {
                return ResourceManager.GetString("NumberOfSockets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Of.
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на On foot.
        /// </summary>
        public static string OnFoot {
            get {
                return ResourceManager.GetString("OnFoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на On monowheel.
        /// </summary>
        public static string OnMonowheel {
            get {
                return ResourceManager.GetString("OnMonowheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на On moped.
        /// </summary>
        public static string OnMoped {
            get {
                return ResourceManager.GetString("OnMoped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на On motorcycle.
        /// </summary>
        public static string OnMotorcycle {
            get {
                return ResourceManager.GetString("OnMotorcycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на On scooter.
        /// </summary>
        public static string OnScooterA {
            get {
                return ResourceManager.GetString("OnScooterA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на On scooter.
        /// </summary>
        public static string OnScooterB {
            get {
                return ResourceManager.GetString("OnScooterB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Operating system.
        /// </summary>
        public static string OperatingSystem {
            get {
                return ResourceManager.GetString("OperatingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Optical Disc.
        /// </summary>
        public static string OpticalDisc {
            get {
                return ResourceManager.GetString("OpticalDisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Optical drive.
        /// </summary>
        public static string OpticalDrive {
            get {
                return ResourceManager.GetString("OpticalDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Overload protection.
        /// </summary>
        public static string OverloadProtection {
            get {
                return ResourceManager.GetString("OverloadProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Overvoltage protection.
        /// </summary>
        public static string OvervoltageProtection {
            get {
                return ResourceManager.GetString("OvervoltageProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pantry.
        /// </summary>
        public static string Pantry {
            get {
                return ResourceManager.GetString("Pantry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pantry size.
        /// </summary>
        public static string PantrySize {
            get {
                return ResourceManager.GetString("PantrySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Partition.
        /// </summary>
        public static string Partition {
            get {
                return ResourceManager.GetString("Partition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pay.
        /// </summary>
        public static string Pay {
            get {
                return ResourceManager.GetString("Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Payment for public transport.
        /// </summary>
        public static string PaymentForPublicTransport {
            get {
                return ResourceManager.GetString("PaymentForPublicTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PCI-Express 2.0 support.
        /// </summary>
        public static string PCIExpress20Support {
            get {
                return ResourceManager.GetString("PCIExpress20Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PCI-Express 3.0 support.
        /// </summary>
        public static string PCIExpress30Support {
            get {
                return ResourceManager.GetString("PCIExpress30Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Penalty for unpaid fare.
        /// </summary>
        public static string PenaltyForUnpaidFare {
            get {
                return ResourceManager.GetString("PenaltyForUnpaidFare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Places for fans.
        /// </summary>
        public static string PlacesForFans {
            get {
                return ResourceManager.GetString("PlacesForFans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Player.
        /// </summary>
        public static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Player name.
        /// </summary>
        public static string PlayerName {
            get {
                return ResourceManager.GetString("PlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Power.
        /// </summary>
        public static string Power {
            get {
                return ResourceManager.GetString("Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Power to the motherboard.
        /// </summary>
        public static string PowerToTheMotherboard {
            get {
                return ResourceManager.GetString("PowerToTheMotherboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Program.
        /// </summary>
        public static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PS/2 for keyboard.
        /// </summary>
        public static string PS2ForKeyboard {
            get {
                return ResourceManager.GetString("PS2ForKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PS/2 for mouse.
        /// </summary>
        public static string PS2ForMouse {
            get {
                return ResourceManager.GetString("PS2ForMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Power supply unit.
        /// </summary>
        public static string PSU {
            get {
                return ResourceManager.GetString("PSU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pull out.
        /// </summary>
        public static string PullOut {
            get {
                return ResourceManager.GetString("PullOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Purse.
        /// </summary>
        public static string Purse {
            get {
                return ResourceManager.GetString("Purse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Random access memory.
        /// </summary>
        public static string RAM {
            get {
                return ResourceManager.GetString("RAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Read speed.
        /// </summary>
        public static string ReadSpeed {
            get {
                return ResourceManager.GetString("ReadSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Receipt of funds.
        /// </summary>
        public static string ReceiptOfFunds {
            get {
                return ResourceManager.GetString("ReceiptOfFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Received.
        /// </summary>
        public static string Received {
            get {
                return ResourceManager.GetString("Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rent price.
        /// </summary>
        public static string RentPrice {
            get {
                return ResourceManager.GetString("RentPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resolution.
        /// </summary>
        public static string Resolution {
            get {
                return ResourceManager.GetString("Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save assembly.
        /// </summary>
        public static string SaveAssembly {
            get {
                return ResourceManager.GetString("SaveAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scenario.
        /// </summary>
        public static string Scenario {
            get {
                return ResourceManager.GetString("Scenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scenario settings.
        /// </summary>
        public static string ScenarioSettings {
            get {
                return ResourceManager.GetString("ScenarioSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sections.
        /// </summary>
        public static string Sections {
            get {
                return ResourceManager.GetString("Sections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shop.
        /// </summary>
        public static string Shop {
            get {
                return ResourceManager.GetString("Shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Short circuit protection.
        /// </summary>
        public static string ShortCircuitProtection {
            get {
                return ResourceManager.GetString("ShortCircuitProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shutdown.
        /// </summary>
        public static string Shutdown {
            get {
                return ResourceManager.GetString("Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Socket.
        /// </summary>
        public static string Socket {
            get {
                return ResourceManager.GetString("Socket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Speed control.
        /// </summary>
        public static string SpeedControl {
            get {
                return ResourceManager.GetString("SpeedControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start a new game.
        /// </summary>
        public static string StartNewGame {
            get {
                return ResourceManager.GetString("StartNewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Testing and running.
        /// </summary>
        public static string TestingAndRunning {
            get {
                return ResourceManager.GetString("TestingAndRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The number of PCI buses.
        /// </summary>
        public static string TheNumberOfPCIBuses {
            get {
                return ResourceManager.GetString("TheNumberOfPCIBuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The number of pins PCI-E 6.
        /// </summary>
        public static string TheNumberOfPinsPCIE6 {
            get {
                return ResourceManager.GetString("TheNumberOfPinsPCIE6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The number of pins PCI-E 8.
        /// </summary>
        public static string TheNumberOfPinsPCIE8 {
            get {
                return ResourceManager.GetString("TheNumberOfPinsPCIE8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The presence of a sound card.
        /// </summary>
        public static string ThePresenceOfASoundCard {
            get {
                return ResourceManager.GetString("ThePresenceOfASoundCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type case.
        /// </summary>
        public static string TypeСase {
            get {
                return ResourceManager.GetString("TypeСase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Under.
        /// </summary>
        public static string Under {
            get {
                return ResourceManager.GetString("Under", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на USB 2.0 sockets.
        /// </summary>
        public static string USB20Sockets {
            get {
                return ResourceManager.GetString("USB20Sockets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на USB 3.0 sockets.
        /// </summary>
        public static string USB30Sockets {
            get {
                return ResourceManager.GetString("USB30Sockets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Video card.
        /// </summary>
        public static string VideoCard {
            get {
                return ResourceManager.GetString("VideoCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Voltage.
        /// </summary>
        public static string Voltage {
            get {
                return ResourceManager.GetString("Voltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Volume.
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Week.
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на What are we going to get to?.
        /// </summary>
        public static string WhatAreWeGoingToGetTo {
            get {
                return ResourceManager.GetString("WhatAreWeGoingToGetTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Write speed.
        /// </summary>
        public static string WriteSpeed {
            get {
                return ResourceManager.GetString("WriteSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} support.
        /// </summary>
        public static string XSupport {
            get {
                return ResourceManager.GetString("XSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You could not pay a fine for an unpaid fare..
        /// </summary>
        public static string YouCouldNotPayAFineForAnUnpaidFare {
            get {
                return ResourceManager.GetString("YouCouldNotPayAFineForAnUnpaidFare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You do not have a computer.
        /// </summary>
        public static string YouDoNotHaveComputer {
            get {
                return ResourceManager.GetString("YouDoNotHaveComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You do not have enough money!.
        /// </summary>
        public static string YouDoNotHaveEnoughMoney {
            get {
                return ResourceManager.GetString("YouDoNotHaveEnoughMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You want to buy a ticket for.
        /// </summary>
        public static string YouWantToBuyATicketFor {
            get {
                return ResourceManager.GetString("YouWantToBuyATicketFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You were charged for unpaid fare!.
        /// </summary>
        public static string YouWereChargedForUnpaidFare {
            get {
                return ResourceManager.GetString("YouWereChargedForUnpaidFare", resourceCulture);
            }
        }
    }
}
