//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Computer_Era_X.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Computer_Era_X.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About the author.
        /// </summary>
        public static string _ {
            get {
                return ResourceManager.GetString("+", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add assembly.
        /// </summary>
        public static string AddAssembly {
            get {
                return ResourceManager.GetString("AddAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Assembling added.
        /// </summary>
        public static string AssemblingAdded {
            get {
                return ResourceManager.GetString("AssemblingAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Assembling changed.
        /// </summary>
        public static string AssemblingChanged {
            get {
                return ResourceManager.GetString("AssemblingChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The specified name is already in the list of assemblies..
        /// </summary>
        public static string AssemblyMessage1 {
            get {
                return ResourceManager.GetString("AssemblyMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Assembly name.
        /// </summary>
        public static string AssemblyName {
            get {
                return ResourceManager.GetString("AssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type.
        /// </summary>
        public static string AssemblyType {
            get {
                return ResourceManager.GetString("AssemblyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bank &quot;Retribution&quot;.
        /// </summary>
        public static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Before.
        /// </summary>
        public static string Before {
            get {
                return ResourceManager.GetString("Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bus park №1.
        /// </summary>
        public static string BusParkNumberOne {
            get {
                return ResourceManager.GetString("BusParkNumberOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By bike.
        /// </summary>
        public static string ByBike {
            get {
                return ResourceManager.GetString("ByBike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By car.
        /// </summary>
        public static string ByCar {
            get {
                return ResourceManager.GetString("ByCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By public transport.
        /// </summary>
        public static string ByPublicTransport {
            get {
                return ResourceManager.GetString("ByPublicTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Case.
        /// </summary>
        public static string Case {
            get {
                return ResourceManager.GetString("Case", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cells.
        /// </summary>
        public static string Cells {
            get {
                return ResourceManager.GetString("Cells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shop &quot;Spike yourself&quot;.
        /// </summary>
        public static string ComponentStoreFullName {
            get {
                return ResourceManager.GetString("ComponentStoreFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Spike yourself.
        /// </summary>
        public static string ComponentStoreName {
            get {
                return ResourceManager.GetString("ComponentStoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Computer.
        /// </summary>
        public static string Computer {
            get {
                return ResourceManager.GetString("Computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Continue.
        /// </summary>
        public static string ContinueGame {
            get {
                return ResourceManager.GetString("ContinueGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cost.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Central processing unit.
        /// </summary>
        public static string CPU {
            get {
                return ResourceManager.GetString("CPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CPU cooler.
        /// </summary>
        public static string CPUCooler {
            get {
                return ResourceManager.GetString("CPUCooler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CPU frequency.
        /// </summary>
        public static string CPUFrequency {
            get {
                return ResourceManager.GetString("CPUFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date of service contract.
        /// </summary>
        public static string DateOfServiceContract {
            get {
                return ResourceManager.GetString("DateOfServiceContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete all notifications.
        /// </summary>
        public static string DeleteAllNotifications {
            get {
                return ResourceManager.GetString("DeleteAllNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Distance to city center.
        /// </summary>
        public static string DistanceToCityCenter {
            get {
                return ResourceManager.GetString("DistanceToCityCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No central processing unit.
        /// </summary>
        public static string ErrorСodeNoCPU {
            get {
                return ResourceManager.GetString("ErrorСodeNoCPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No CPU cooler.
        /// </summary>
        public static string ErrorСodeNoCPUCooler {
            get {
                return ResourceManager.GetString("ErrorСodeNoCPUCooler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No hard disk drive.
        /// </summary>
        public static string ErrorСodeNoHDD {
            get {
                return ResourceManager.GetString("ErrorСodeNoHDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No motherboard.
        /// </summary>
        public static string ErrorСodeNoMotherboard {
            get {
                return ResourceManager.GetString("ErrorСodeNoMotherboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No power supply unit.
        /// </summary>
        public static string ErrorСodeNoPowerSupply {
            get {
                return ResourceManager.GetString("ErrorСodeNoPowerSupply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No random access memory.
        /// </summary>
        public static string ErrorСodeNoRAM {
            get {
                return ResourceManager.GetString("ErrorСodeNoRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No video card.
        /// </summary>
        public static string ErrorСodeNoVideoСard {
            get {
                return ResourceManager.GetString("ErrorСodeNoVideoСard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ok.
        /// </summary>
        public static string ErrorСodeOk {
            get {
                return ResourceManager.GetString("ErrorСodeOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Found on the road.
        /// </summary>
        public static string FoundOnTheRoad {
            get {
                return ResourceManager.GetString("FoundOnTheRoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Free.
        /// </summary>
        public static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на It turns out walking in the air is useful not only for health but also for pocket. You found {0} {1} on the road..
        /// </summary>
        public static string GameMessage1 {
            get {
                return ResourceManager.GetString("GameMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hard disk drive.
        /// </summary>
        public static string HDD {
            get {
                return ResourceManager.GetString("HDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Heat dissipation.
        /// </summary>
        public static string HeatDissipation {
            get {
                return ResourceManager.GetString("HeatDissipation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hour.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Install.
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Installation.
        /// </summary>
        public static string Installation {
            get {
                return ResourceManager.GetString("Installation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Installation of components.
        /// </summary>
        public static string InstallationOfComponents {
            get {
                return ResourceManager.GetString("InstallationOfComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid scenario configuration value.
        /// </summary>
        public static string InvalidScenarioConfigurationValue {
            get {
                return ResourceManager.GetString("InvalidScenarioConfigurationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invested.
        /// </summary>
        public static string Invested {
            get {
                return ResourceManager.GetString("Invested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Keyboard.
        /// </summary>
        public static string Keyboard {
            get {
                return ResourceManager.GetString("Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Launch.
        /// </summary>
        public static string Launch {
            get {
                return ResourceManager.GetString("Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Local disk.
        /// </summary>
        public static string LocalDisk {
            get {
                return ResourceManager.GetString("LocalDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Main.
        /// </summary>
        public static string MainScenario {
            get {
                return ResourceManager.GetString("MainScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parents.
        /// </summary>
        public static string MainScenarioPaymentInitiator {
            get {
                return ResourceManager.GetString("MainScenarioPaymentInitiator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Starting capital.
        /// </summary>
        public static string MainScenarioPaymentName {
            get {
                return ResourceManager.GetString("MainScenarioPaymentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum working temperature.
        /// </summary>
        public static string MaximumWorkingTemperature {
            get {
                return ResourceManager.GetString("MaximumWorkingTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minute.
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Modified assembly.
        /// </summary>
        public static string ModifiedAssembly {
            get {
                return ResourceManager.GetString("ModifiedAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Monitor.
        /// </summary>
        public static string Monitor {
            get {
                return ResourceManager.GetString("Monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Motherboard.
        /// </summary>
        public static string Motherboard {
            get {
                return ResourceManager.GetString("Motherboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mouse.
        /// </summary>
        public static string Mouse {
            get {
                return ResourceManager.GetString("Mouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Moving in space and time.
        /// </summary>
        public static string MovingInSpaceAndTime {
            get {
                return ResourceManager.GetString("MovingInSpaceAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Game.
        /// </summary>
        public static string NewGame {
            get {
                return ResourceManager.GetString("NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No player name entered.
        /// </summary>
        public static string NoPlayerNameEntered {
            get {
                return ResourceManager.GetString("NoPlayerNameEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Normal speed.
        /// </summary>
        public static string NormalSpeed {
            get {
                return ResourceManager.GetString("NormalSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No scenario selected.
        /// </summary>
        public static string NoScenarioSelected {
            get {
                return ResourceManager.GetString("NoScenarioSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not limited.
        /// </summary>
        public static string NotLimited {
            get {
                return ResourceManager.GetString("NotLimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No value selected in scenario settings.
        /// </summary>
        public static string NoValueSelectedInScenarioSettings {
            get {
                return ResourceManager.GetString("NoValueSelectedInScenarioSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of cores.
        /// </summary>
        public static string NumberOfCores {
            get {
                return ResourceManager.GetString("NumberOfCores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Of.
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на On foot.
        /// </summary>
        public static string OnFoot {
            get {
                return ResourceManager.GetString("OnFoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на On monowheel.
        /// </summary>
        public static string OnMonowheel {
            get {
                return ResourceManager.GetString("OnMonowheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на On moped.
        /// </summary>
        public static string OnMoped {
            get {
                return ResourceManager.GetString("OnMoped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на On motorcycle.
        /// </summary>
        public static string OnMotorcycle {
            get {
                return ResourceManager.GetString("OnMotorcycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на On scooter.
        /// </summary>
        public static string OnScooterA {
            get {
                return ResourceManager.GetString("OnScooterA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на On scooter.
        /// </summary>
        public static string OnScooterB {
            get {
                return ResourceManager.GetString("OnScooterB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Operating system.
        /// </summary>
        public static string OperatingSystem {
            get {
                return ResourceManager.GetString("OperatingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Optical Disc.
        /// </summary>
        public static string OpticalDisc {
            get {
                return ResourceManager.GetString("OpticalDisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Optical drive.
        /// </summary>
        public static string OpticalDrive {
            get {
                return ResourceManager.GetString("OpticalDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pantry.
        /// </summary>
        public static string Pantry {
            get {
                return ResourceManager.GetString("Pantry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pantry size.
        /// </summary>
        public static string PantrySize {
            get {
                return ResourceManager.GetString("PantrySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Partition.
        /// </summary>
        public static string Partition {
            get {
                return ResourceManager.GetString("Partition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Penalty for unpaid fare.
        /// </summary>
        public static string PenaltyForUnpaidFare {
            get {
                return ResourceManager.GetString("PenaltyForUnpaidFare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Player.
        /// </summary>
        public static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Player name.
        /// </summary>
        public static string PlayerName {
            get {
                return ResourceManager.GetString("PlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Program.
        /// </summary>
        public static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Power supply unit.
        /// </summary>
        public static string PSU {
            get {
                return ResourceManager.GetString("PSU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pull out.
        /// </summary>
        public static string PullOut {
            get {
                return ResourceManager.GetString("PullOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Purse.
        /// </summary>
        public static string Purse {
            get {
                return ResourceManager.GetString("Purse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Random access memory.
        /// </summary>
        public static string RAM {
            get {
                return ResourceManager.GetString("RAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Receipt of funds.
        /// </summary>
        public static string ReceiptOfFunds {
            get {
                return ResourceManager.GetString("ReceiptOfFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Received.
        /// </summary>
        public static string Received {
            get {
                return ResourceManager.GetString("Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rent price.
        /// </summary>
        public static string RentPrice {
            get {
                return ResourceManager.GetString("RentPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save assembly.
        /// </summary>
        public static string SaveAssembly {
            get {
                return ResourceManager.GetString("SaveAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scenario.
        /// </summary>
        public static string Scenario {
            get {
                return ResourceManager.GetString("Scenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scenario settings.
        /// </summary>
        public static string ScenarioSettings {
            get {
                return ResourceManager.GetString("ScenarioSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shop.
        /// </summary>
        public static string Shop {
            get {
                return ResourceManager.GetString("Shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shutdown.
        /// </summary>
        public static string Shutdown {
            get {
                return ResourceManager.GetString("Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Socket.
        /// </summary>
        public static string Socket {
            get {
                return ResourceManager.GetString("Socket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start a new game.
        /// </summary>
        public static string StartNewGame {
            get {
                return ResourceManager.GetString("StartNewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Testing and running.
        /// </summary>
        public static string TestingAndRunning {
            get {
                return ResourceManager.GetString("TestingAndRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Under.
        /// </summary>
        public static string Under {
            get {
                return ResourceManager.GetString("Under", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Video card.
        /// </summary>
        public static string VideoCard {
            get {
                return ResourceManager.GetString("VideoCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Week.
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на What are we going to get to?.
        /// </summary>
        public static string WhatAreWeGoingToGetTo {
            get {
                return ResourceManager.GetString("WhatAreWeGoingToGetTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You could not pay a fine for an unpaid fare..
        /// </summary>
        public static string YouCouldNotPayAFineForAnUnpaidFare {
            get {
                return ResourceManager.GetString("YouCouldNotPayAFineForAnUnpaidFare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You do not have a computer.
        /// </summary>
        public static string YouDoNotHaveComputer {
            get {
                return ResourceManager.GetString("YouDoNotHaveComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You were charged for unpaid fare!.
        /// </summary>
        public static string YouWereChargedForUnpaidFare {
            get {
                return ResourceManager.GetString("YouWereChargedForUnpaidFare", resourceCulture);
            }
        }
    }
}
